import Banner from "@/components/Banner/Banner";
import BannerGift from "@/components/Banner/BannerGift";
import ProductList from "@/components/Product/ProductList";
import authSlice from "@/redux/features/auth/authSlice";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useDispatch } from "react-redux";

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const onLogin = () => {};
  return (
    <div className={""}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bodyIdx">
        <Banner />
        <div className="container">
          {/* <Banner /> */}
          <BannerGift />
          <div className="main">
            <div className="main__wp1">
              <div className="main__wp1___title">
                <h4>
                  <picture>
                    <img src={"/images/new-items.png"} alt="" />
                  </picture>
                  Khám phá quản mới
                </h4>
                <div className="alw">
                  <i className="fa-size fa-solid fa-paperclip" />
                </div>
              </div>
              <ProductList />
            </div>
            <div className="main__wp1">
              <div className="main__wp1___title">
                <h4>
                  <picture>
                    <img src={"/images/new-items.png"} alt="" />
                  </picture>
                  Khám phá quản mới
                </h4>
                <div className="alw">
                  <i className="fa-size fa-solid fa-paperclip" />
                </div>
              </div>
              <ProductList />
            </div>
            <div className="main__wp1">
              <div className="main__wp1___title">
                <h4>
                  <picture>
                    <img src={"/images/new-items.png"} alt="" />
                  </picture>
                  Khám phá quản mới
                </h4>
                <div className="alw">
                  <i className="fa-size fa-solid fa-paperclip" />
                </div>
              </div>
              <ProductList />
            </div>
            <div className="main__wp1">
              <div className="main__wp1___title">
                <h4>
                  <picture>
                    <img src={"/images/new-items.png"} alt="" />
                  </picture>
                  Khám phá quản mới
                </h4>
                <div className="alw">
                  <i className="fa-size fa-solid fa-paperclip" />
                </div>
              </div>
              <ProductList />
            </div>
          </div>
          {/* <Trademark /> */}
        </div>
      </div>
    </div>
  );
};

export default Home;
